[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/mystery-crimes.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/mystery-crimes.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
